# Generated by Django 3.2.6 on 2021-08-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210824_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='freight',
            field=models.CharField(choices=[('TR', 'Train'), ('AR', 'Airplane'), ('CA', 'Car')], max_length=10),
        ),
    ]
